.\" Macros
.\" define indentation for suboptions
.nr SS 5
.de IPs
.IP "\\$1" \n(SS
..
.TH "dwell-click-applet" 1
.SH NAME
dwell-click-applet \- Useful to select click type when using dwell click
.SH SYNOPSIS
No command line interface.
.SH DESCRIPTION
The Dwell Click panel is part of the mousetweaks package. It can be used in conjuction with the dwell click function that resides in the Accessibility tab of the Mouse control panel. By clicking on the items on the Dwell Click panel, the user specifies to the dwell function in the "choose type of click beforehand" mode, what automatic click type to perform next.
.SH OPTIONS
The \fBPointer Capture\fR panel applet does not have any command line interface.
.SH FILES
.I /usr/bin/dwell\-click\-applet
.SH BUGS
See:
.I http://bugzilla.gnome.org/
.SH AUTHORS
Gerd Kohlberger <gerdk@svn.gnome.org>
.SH LICENSE
Licenced under the GNU General Public License v3 and later
.SH SEE ALSO
Assistive Technology Service Provider Interface (AT\-SPI)
