.TH "mousetweaks" 1
.SH NAME
mousetweaks \- Accessibility enhancements for pointing devices
.SH SYNOPSIS
.B mousetweaks
[\-\-dwell] [\-\-ssc]
[\-\-dwell\-time=FLOAT] [\-\-ssc\-time=FLOAT]
[\-m|\-\-dwell\-mode=STRING] [\-c|\-\-show\-ctw]
[\-t|\-\-threshold=INT] [\-g|\-\-geometry]
[\-s|\-\-shutdown]
[\-\-daemonize] [\-?|\-\-help]
.SH DESCRIPTION
.B mousetweaks
is a collection of accessibility enhancements for pointing devices. This
manual page describes the mousetweaks daemon.
.SH OPTIONS
.TP
.B \-\-dwell
Automatically perform mouse clicks without using a physical button.
.TP
.B \-\-ssc
Trigger the secondary mouse button when the primary mouse button is held down
for a specified amount of time.
.TP
.B \-\-dwell\-time=FLOAT
Time to keep the pointer motionless before a dwell click is performed.
Range: 0.2 \- 3.0 seconds.
.TP
.B \-\-ssc\-time=FLOAT
Time to hold the primary mouse button before a simulated secondary
click is performed. Range: 0.5 \- 3.0 seconds.
.TP
.B \-m, \-\-dwell\-mode=STRING
Select a dwell mode. Available options:
.B window
\- Select the click type from a window or a panel applet.
.B gesture
\- Perform different clicks by moving in different directions.
.TP
.B \-c, \-\-show\-ctw
Show the click\-type window. Only useful in combination with \-\-dwell\-mode=window.
.TP
.B \-t, \-\-threshold=INT
Ignore small pointer movements. Range: 0 \- 30 pixels.
.TP
.B \-g, \-\-geometry
Size and position of the click-type window. Expects a standard X Window System
geometry string. ie. WIDTHxHEIGHT+X+Y
.TP
.B \-s, \-\-shutdown
Stop the mousetweaks daemon.
.TP
.B \-\-daemonize
Start mousetweaks in the background, ie. spawn a child process.
.TP
.B \-\-login
Start mousetweaks in login mode. Login mode enables workarounds specific
to GDM. Currently unused.
.SH FILES
.I mousetweaks.pid
.RS
The daemon creates a lock file in the $XDG_RUNTIME_DIR directory to keep track
of its state. On systems with no user runtime directory, the $XDG_CACHE_HOME
directory is used.
.SH BUGS
Report bugs to
.UR http://bugzilla.gnome.org/
<http://bugzilla.gnome.org/>
.UE
.SH AUTHORS
This manual page was written by Francesco Fumanti.
.SH LICENSE
Licenced under the GNU General Public License v3 or later.
