.\" Macros
.\" define indentation for suboptions
.nr SS 5
.de IPs
.IP "\\$1" \n(SS
..
.TH "pointer-capture-applet" 1
.SH NAME
pointer-capture-applet \- Creates an area on the panel to capture the pointer
.SH SYNOPSIS
No command line interface.
.SH DESCRIPTION
The Pointer Capture applet creates an area on the panel into which the pointer can be captured until the user releases it with a predefined button and modifier combination.
.SH OPTIONS
The \fBPointer Capture\fR panel applet does not have any command line interface.
.SH FILES
.I /usr/bin/pointer\-capture\-applet
.SH BUGS
See:
.I http://bugzilla.gnome.org
.SH AUTHORS
Gerd Kohlberger <gerdk@svn.gnome.org>
.SH LICENSE
Licenced under the GNU General Public License v3 and later
.SH SEE ALSO
Assistive Technology Service Provider Interface (AT\-SPI)
