.TH "pointer-capture-applet" 1
.SH NAME
pointer\-capture\-applet \- Creates an area on the panel to capture the pointer
.SH SYNOPSIS
.B pointer\-capture\-applet
.SH DESCRIPTION
The Pointer Capture applet is part of the mousetweaks package. It creates an area on the panel which can capture the pointer until the user releases it with a predefined button and modifier key combination.
.SH BUGS
Report bugs to
.UR http://bugzilla.gnome.org/
<http://bugzilla.gnome.org/>
.UE
.SH AUTHORS
.B pointer\-capture\-applet
was written by Gerd Kohlberger <lowfi@chello.at>. This manual page was written by Francesco Fumanti <francesco.fumanti@gmx.net>
.SH LICENSE
Licenced under the GNU General Public License v3 or later.
.SH SEE ALSO
.BR "mousetweaks" (1),
.BR "dwell\-click\-applet" (1),
Assistive Technology Service Provider Interface (AT\-SPI)
